=== LaughingRover/TLC/xml/XMLIntro.dtd
<!ELEMENT fileSystem (type)>
<!ELEMENT type (permissions, linkCount, owner, group, fileSize, lastAccessDate, name, symbolicLink)>
<!ELEMENT permissions (userPermissions | groupPermissions| otherPermissions)*>
<!ELEMENT userPermissions (#PCDATA) >
<!ELEMENT groupPermissions (#PCDATA)>
<!ELEMENT otherPermissions (#PCDATA)>
<!ELEMENT linkCount (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT fileSize (#PCDATA)>
<!ELEMENT lastAccessDate (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT symbolicLink (#PCDATA)>

=== LaughingRover/TLC/xml/XMLIntro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fileSystem SYSTEM "XMLIntro.dtd">

<fileSystem>
	<type>
		<permissions>
			<userPermissions />
			<groupPermissions />
			<otherPermissions />
		</permissions>

		<linkCount />
		<owner />
		<group />
		<fileSize />
		<lastAccessDate />
		<name />
		<symbolicLink />
	</type>
</fileSystem>
